package com.cbs.account_service.entity;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.cbs.account_service.enums.AccountStatus;
import com.cbs.account_service.enums.AccountType;
import com.cbs.account_service.exception.AccountOperationException;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Core account entity.
 *
 * Key design decisions:
 * ─────────────────────
 * 1. balance field is a CACHE of the ledger sum.
 *    The Ledger Service owns the source of truth.
 *    Reads come from this cache; writes go through the Transaction Service
 *    which updates both ledger_entries AND this balance atomically.
 *
 * 2. BigDecimal (not double/float) for all monetary fields.
 *    Mapped to PostgreSQL NUMERIC(18,2).
 *
 * 3. @Version for optimistic locking — prevents two concurrent threads
 *    from reading balance=1000, both approving a ₹800 withdrawal,
 *    and both writing balance=200 (money created from thin air).
 *    The second update throws OptimisticLockException → service retries.
 *
 * 4. Domain methods (freeze, unfreeze, close, activate) encapsulate
 *    business rules directly on the entity (rich domain model).
 */
@Entity
@Table(
    name = "accounts",
    indexes = {
        @Index(name = "idx_accounts_number",   columnList = "account_number", unique = true),
        @Index(name = "idx_accounts_customer", columnList = "customer_id"),
        @Index(name = "idx_accounts_status",   columnList = "status")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "account_id", updatable = false, nullable = false)
    private UUID accountId;

    // ── Ownership ────────────────────────────────────────────────
    @Column(name = "customer_id", nullable = false, updatable = false)
    private UUID customerId;

    @Column(name = "branch_id", nullable = false, updatable = false)
    private UUID branchId;

    // ── Identity ──────────────────────────────────────────────────
    /**
     * Human-readable account number. Generated by PostgreSQL sequence
     * (seq_account_number) in the DB default expression. The JPA entity
     * reads it back after insert — do NOT generate in Java.
     * Format: CBS + 11-digit zero-padded sequence  e.g. CBS00000001001
     */
    @Column(name = "account_number", nullable = false, unique = true, updatable = false)
    private String accountNumber;

    // ── Type & Currency ───────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false, updatable = false, length = 25)
    private AccountType accountType;

    @Column(name = "currency", nullable = false, length = 3)
    @Builder.Default
    private String currency = "INR";

    // ── Balance fields (NUMERIC(18,2) in DB) ─────────────────────
    @Column(name = "balance", nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal balance = BigDecimal.ZERO;

    /**
     * Funds on hold: cheque clearing, UPI mandate blocks, court holds.
     * available = balance - holdAmount + overdraftLimit
     */
    @Column(name = "hold_amount", nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal holdAmount = BigDecimal.ZERO;

    /**
     * Maximum debit beyond zero. Only for CURRENT / OVERDRAFT / LOAN types.
     * Enforced at DB level via CHECK constraint.
     */
    @Column(name = "overdraft_limit", nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal overdraftLimit = BigDecimal.ZERO;

    @Column(name = "minimum_balance", nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal minimumBalance = BigDecimal.ZERO;

    // ── Interest ──────────────────────────────────────────────────
    @Column(name = "interest_rate", precision = 5, scale = 2)
    private BigDecimal interestRate;

    @Column(name = "last_interest_calc_date")
    private LocalDate lastInterestCalcDate;

    // ── Status & Lifecycle ────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 25)
    @Builder.Default
    private AccountStatus status = AccountStatus.PENDING_ACTIVATION;

    @Column(name = "activated_at")
    private OffsetDateTime activatedAt;

    @Column(name = "dormant_since")
    private LocalDate dormantSince;

    @Column(name = "closed_at")
    private OffsetDateTime closedAt;

    @Column(name = "closure_reason", length = 200)
    private String closureReason;

    // ── Term Deposit fields (FD / RD only) ───────────────────────
    @Column(name = "maturity_date")
    private LocalDate maturityDate;

    @Column(name = "maturity_amount", precision = 18, scale = 2)
    private BigDecimal maturityAmount;

    /** FD/RD must link to a parent savings/current account for interest credit. */
    @Column(name = "parent_account_id")
    private UUID parentAccountId;

    // ── Nominee ───────────────────────────────────────────────────
    @Column(name = "nominee_name", length = 120)
    private String nomineeName;

    @Column(name = "nominee_relation", length = 60)
    private String nomineeRelation;

    @Column(name = "nominee_dob")
    private LocalDate nomineeDob;

    // ── Flags ─────────────────────────────────────────────────────
    @Column(name = "is_joint_account", nullable = false)
    @Builder.Default
    private Boolean isJointAccount = false;

    @Column(name = "is_nri_account", nullable = false)
    @Builder.Default
    private Boolean isNriAccount = false;

    /**
     * Quick-freeze flag set by Fraud Detection Service.
     * Separate from status = FROZEN (which is a formal bank/court order).
     * is_frozen=true can be reversed instantly by the fraud system.
     */
    @Column(name = "is_frozen", nullable = false)
    @Builder.Default
    private Boolean isFrozen = false;

    // ── Audit ─────────────────────────────────────────────────────
    @Column(name = "created_by")
    private UUID createdBy;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /**
     * Optimistic lock version — prevents lost-update race conditions
     * on concurrent balance reads + writes.
     */
    @Version
    @Column(name = "version", nullable = false)
    @Builder.Default
    private Long version = 0L;

    // ─────────────────────────────────────────────────────────────
    // COMPUTED PROPERTIES
    // ─────────────────────────────────────────────────────────────

    /**
     * The amount the customer can actually spend right now.
     * Never persist this — always compute on the fly.
     */
    @Transient
    public BigDecimal getAvailableBalance() {
        return balance
            .subtract(holdAmount)
            .add(overdraftLimit);
    }

    /**
     * True if the account can debit the given amount right now.
     */
    @Transient
    public boolean canDebit(BigDecimal amount) {
        return isOperational() && getAvailableBalance().compareTo(amount) >= 0;
    }

    @Transient
    public boolean isOperational() {
        return status == AccountStatus.ACTIVE && !isFrozen;
    }

    // ─────────────────────────────────────────────────────────────
    // DOMAIN METHODS — business state transitions
    // ─────────────────────────────────────────────────────────────

    public void activate() {
        if (this.status != AccountStatus.PENDING_ACTIVATION) {
            throw new AccountOperationException(
                "Only PENDING_ACTIVATION accounts can be activated. Current: " + status);
        }
        this.status      = AccountStatus.ACTIVE;
        this.activatedAt = OffsetDateTime.now();
    }

    public void freeze(String reason) {
        if (this.status == AccountStatus.CLOSED) {
            throw new AccountOperationException("Cannot freeze a CLOSED account.");
        }
        this.status = AccountStatus.FROZEN;
        // Store reason in closureReason field temporarily (reuse the column)
        this.closureReason = reason;
    }

    public void quickFreeze() {
        // Fraud-detection quick freeze — does NOT change status
        this.isFrozen = true;
    }

    public void quickUnfreeze() {
        this.isFrozen = false;
    }

    public void markDormant() {
        if (this.status != AccountStatus.ACTIVE) {
            throw new AccountOperationException("Only ACTIVE accounts can become DORMANT.");
        }
        this.status      = AccountStatus.DORMANT;
        this.dormantSince = LocalDate.now();
    }

    public void reactivateFromDormant() {
        if (this.status != AccountStatus.DORMANT) {
            throw new AccountOperationException("Account is not DORMANT.");
        }
        this.status      = AccountStatus.ACTIVE;
        this.dormantSince = null;
    }

    public void close(String reason) {
        if (this.status == AccountStatus.CLOSED) {
            throw new AccountOperationException("Account is already CLOSED.");
        }
        if (this.balance.compareTo(BigDecimal.ZERO) != 0) {
            throw new AccountOperationException(
                "Cannot close account with non-zero balance: " + balance);
        }
        this.status        = AccountStatus.CLOSED;
        this.closedAt      = OffsetDateTime.now();
        this.closureReason = reason;
    }

    /** Called by the Transaction Service ONLY — never from business logic. */
    public void applyBalanceDelta(BigDecimal delta) {
        this.balance = this.balance.add(delta);
        if (this.balance.compareTo(overdraftLimit.negate()) < 0) {
            throw new AccountOperationException(
                "Balance " + this.balance + " would exceed overdraft limit of -" + overdraftLimit);
        }
    }

    public void placeHold(BigDecimal amount) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new AccountOperationException("Hold amount must be positive.");
        }
        this.holdAmount = this.holdAmount.add(amount);
    }

    public void releaseHold(BigDecimal amount) {
        BigDecimal newHold = this.holdAmount.subtract(amount);
        if (newHold.compareTo(BigDecimal.ZERO) < 0) {
            throw new AccountOperationException("Cannot release more than held amount.");
        }
        this.holdAmount = newHold;
    }
}